[workspace]
members = [
    "common",
    "api",
    "engine",
    "allocator"
]

resolver = "2"

[workspace.dependencies]
tokio = { version = "1.37.0", features = ["full"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
redis = { version = "0.25.3", features = ["tokio-comp", "json"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
thiserror = "1.0.58"
uuid = { version = "1.8.0", features = ["v4", "serde"] }
axum = "0.7.5"
aws-sdk-gamelift = "1.23.0"
aws-config = "1.1.7"
common = { path = "common" }

[workspace.lints.rust]
warnings = "deny"

[workspace.lints.clippy]
all = "deny"
